.TH NFOVIEW 1 "January 4, 2008"
.SH NAME
nfoview \- viewer for NFO files
.SH SYNOPSIS
.B nfoview
[\fIFILE...\fR]
.SH DESCRIPTION
.PP
.B nfoview
is a simple viewer for NFO files, which are "ASCII" art in the CP437
codepage.  The advantages of using
.B nfoview
instead of a text editor are preset font and encoding settings,
automatic window size and clickable hyperlinks.
.SH AUTHOR
Written by Osmo Salomaa <otsaloma@iki.fi>.
