#!/bin/sh

# Generate a GNU ChangeLog file from old ChangeLog and git logs.

SINCE=27ad7ae19df69bd845aa52e321571c8fc04a5020

cd $(dirname "$0")/..
rm -f ChangeLog
git log --pretty --numstat --summary $SINCE.. | tools/git2cl > ChangeLog
cat tools/data/ChangeLog.old >> ChangeLog
