#!/bin/sh
# Update all translations with new strings.
cd "$(dirname "$0")/../po" || exit 1
intltool-update -m || exit 1
sleep 3 && [ -f missing ] && exit 1
intltool-update -p -g nfoview -x || exit 1
for X in *.po; do msgmerge -UNv "$X" nfoview.pot; done
