name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: >
          sudo apt-get update && sudo apt-get install -y
          flake8
          gettext
          gir1.2-gtk-3.0
          python3
          python3-dev
          python3-gi
          python3-pytest
          xvfb
      - name: Run linter
        run: flake8 .
      - name: Run unit tests
        run: xvfb-run py.test-3 nfoview
      - name: Install
        run: |
          sudo make PREFIX=/usr/local build install clean
          make DESTDIR=pkg PREFIX=/usr build install clean
