name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -c "import sys; print(sys.version)"
      - run: >
          sudo apt-get update && sudo apt-get install -y
          flake8
          gettext
          gir1.2-gtk-4.0
          gir1.2-pango-1.0
          python3
          python3-cairo
          python3-dev
          python3-gi
          python3-pytest
          xvfb

      - run: make check
      - run: xvfb-run pytest-3 .
      - run: sudo make PREFIX=/usr/local build install clean
      - run: sudo make DESTDIR=pkg PREFIX=/usr build install clean
